package com.common;

public enum Status {
	PENDING, BIND_CHECK_APPROVED, BIND_CHECK_DECLINED, QUOTA_CHECK_APPROVED, QUOTA_CHECK_DECLINED, DEDUCTION_SUCCESS,
	DEDUCTION_FAIL, HOST_TEXT_SENDED, TRANSACTION_SUCCESS

}
